### PR TITLE
gitignore: ignore _all_ target directories

### PR DESCRIPTION
**Pull request by PureTryOut**
I several times had a `protocol/target` folder which I kept accidentally committing. Let's ignore that directory (and others).

I'm not entirely sure this does the right thing so needs testing, but right now I can't get the folder to appear again.

### CODE REVIEW

**Comment by terrarier2111** [comment]
I never had issues with the target directory, which IDE are you using?

**Comment by PureTryOut** [comment]
None, just neovim and `cargo run` in a separate terminal :shrug:

**Comment by terrarier2111** [comment]
Oh, okay, i could also be a feature of my IDE, because the target folder is colored differently

**Comment by PureTryOut** [comment]
I had the opportunity to test this now, and it works as expected. Should be ready to merge.

**Pull request merged**
